<?php

/**
 * Malay descriptions for Cuti MY seed data.
 * Keys must match the holiday keys in includes/seed_holidays.php.
 */
return [
    'new_year' => 'Hari pertama kalendar Gregory. Cuti umum di kebanyakan negeri, kecuali Johor, Kedah, Kelantan, Perlis dan Terengganu.',
    'nsb_birthday' => 'Hari keputeraan rasmi Yang di-Pertuan Besar Negeri Sembilan. Cuti negeri untuk Negeri Sembilan sahaja.',
    'thaipusam' => 'Perayaan Hindu sempena perjalanan Lord Murugan. Cuti di Johor, Negeri Sembilan, Pulau Pinang, Perak, Selangor, Kuala Lumpur dan Putrajaya.',
    'ft_day' => 'Memperingati penubuhan Wilayah Persekutuan. Cuti di Kuala Lumpur, Labuan dan Putrajaya.',
    'israk' => 'Memperingati Israk dan Mikraj Nabi Muhammad. Cuti di Kedah, Negeri Sembilan, Perlis dan Terengganu.',
    'cny1' => 'Hari pertama Tahun Baharu Cina mengikut kalendar lunar. Cuti umum persekutuan di seluruh Malaysia.',
    'cny2' => 'Hari kedua Tahun Baharu Cina. Diperhatikan di seluruh negara kecuali Kelantan dan Terengganu.',
    'cny_replacement' => 'Cuti ganti Tahun Baharu Cina apabila hari perayaan jatuh pada hujung minggu.',
    'melaka_independence' => 'Memperingati pengisytiharan tarikh kemerdekaan Melaka. Cuti negeri Melaka.',
    'awal_ramadan' => 'Hari pertama bulan Ramadan. Cuti di Johor dan Kedah.',
    'awal_ramadan_johor' => 'Cuti tambahan Johor sempena Awal Ramadan yang jatuh pada hujung minggu negeri.',
    'terengganu_installation' => 'Ulang tahun pertabalan Sultan Terengganu. Cuti negeri Terengganu.',
    'nuzul' => 'Memperingati penurunan Al-Quran. Cuti di beberapa negeri Semenanjung dan Wilayah Persekutuan.',
    'sultan_johor' => 'Hari keputeraan rasmi Sultan Johor pada 23 Mac setiap tahun. Cuti negeri Johor.',
    'raya1' => 'Hari pertama Aidilfitri, merayakan berakhirnya Ramadan. Cuti umum persekutuan di seluruh Malaysia.',
    'raya2' => 'Hari kedua Aidilfitri. Cuti umum persekutuan di seluruh Malaysia.',
    'raya3_melaka' => 'Cuti tambahan Melaka sempena Aidilfitri.',
    'good_friday' => 'Good Friday dalam kalendar Kristian. Cuti di Sabah dan Sarawak.',
    'melaka_heritage' => 'Memperingati pengisytiharan Melaka sebagai Bandaraya Bersejarah. Cuti negeri Melaka.',
    'sultan_terengganu' => 'Hari keputeraan rasmi Sultan Terengganu pada 26 April. Cuti negeri Terengganu.',
    'labour' => 'Hari Pekerja, cuti umum persekutuan pada 1 Mei di seluruh Malaysia.',
    'wesak' => 'Hari Wesak, memperingati kelahiran, tercerah dan parinirvana Buddha. Cuti umum persekutuan.',
    'wesak_replacement' => 'Cuti ganti Hari Wesak apabila tarikh rasmi jatuh pada hujung minggu atau bercantum dengan cuti lain.',
    'raja_perlis' => 'Hari keputeraan Raja Perlis pada 17 Mei. Cuti negeri Perlis.',
    'hol_pahang' => 'Hari Hol Almarhum Sultan Pahang. Cuti negeri Pahang.',
    'arafah' => 'Hari Arafah, sehari sebelum Aidiladha. Cuti di Kelantan dan Terengganu.',
    'haji1' => 'Hari Raya Aidiladha, memperingati pengorbanan Nabi Ibrahim. Cuti umum persekutuan.',
    'haji2' => 'Hari kedua Aidiladha. Cuti di Kedah, Kelantan, Perlis dan Terengganu.',
    'kaamatan1' => 'Pesta Kaamatan, perayaan menuai Kadazan-Dusun. Cuti di Sabah dan Labuan.',
    'kaamatan2' => 'Hari kedua Pesta Kaamatan di Sabah dan Labuan.',
    'gawai1' => 'Hari Gawai Dayak, perayaan menuai komuniti Dayak. Cuti negeri Sarawak.',
    'gawai2' => 'Hari kedua Gawai Dayak di Sarawak.',
    'agong' => 'Hari keputeraan rasmi Yang di-Pertuan Agong. Cuti umum persekutuan di seluruh Malaysia.',
    'awal_muharram' => 'Awal Muharam / Maal Hijrah, tahun baharu Islam. Cuti umum persekutuan.',
    'sultan_kedah' => 'Hari keputeraan rasmi Sultan Kedah. Cuti negeri Kedah.',
    'penang_heritage' => 'Ulang tahun George Town sebagai Tapak Warisan Dunia UNESCO. Cuti negeri Pulau Pinang.',
    'penang_ydp' => 'Hari jadi Yang di-Pertua Negeri Pulau Pinang. Cuti negeri Pulau Pinang.',
    'hol_iskandar' => 'Hari Hol Almarhum Sultan Iskandar. Cuti negeri Johor.',
    'sarawak_day' => 'Hari Sarawak pada 22 Julai, memperingati pemerintahan sendiri Sarawak. Cuti negeri Sarawak.',
    'sultan_pahang' => 'Hari keputeraan rasmi Sultan Pahang. Cuti negeri Pahang.',
    'melaka_ydp' => 'Hari jadi Yang di-Pertua Negeri Melaka pada 24 Ogos. Cuti negeri Melaka.',
    'maulidur' => 'Maulidur Rasul, hari keputeraan Nabi Muhammad. Cuti umum persekutuan.',
    'merdeka' => 'Hari Kebangsaan / Hari Merdeka pada 31 Ogos 1957. Cuti umum persekutuan.',
    'merdeka_replacement' => 'Cuti ganti Hari Kebangsaan apabila 31 Ogos jatuh pada hari rehat mingguan.',
    'malaysia_day' => 'Hari Malaysia pada 16 September, memperingati pembentukan Malaysia pada 1963.',
    'sultan_kelantan1' => 'Hari pertama keputeraan Sultan Kelantan. Cuti negeri Kelantan.',
    'sultan_kelantan2' => 'Hari kedua keputeraan Sultan Kelantan. Cuti negeri Kelantan.',
    'sabah_ydp' => 'Hari jadi Yang di-Pertua Negeri Sabah. Cuti negeri Sabah.',
    'sarawak_ydp' => 'Hari jadi Yang di-Pertua Negeri Sarawak. Cuti negeri Sarawak.',
    'deepavali' => 'Deepavali, perayaan cahaya komuniti Hindu. Cuti umum kecuali Sarawak.',
    'deepavali_replacement' => 'Cuti ganti Deepavali apabila tarikh rasmi jatuh pada hujung minggu.',
    'sultan_perak' => 'Hari keputeraan rasmi Sultan Perak. Cuti negeri Perak.',
    'sultan_selangor' => 'Hari keputeraan rasmi Sultan Selangor pada 11 Disember. Cuti negeri Selangor.',
    'christmas_eve' => 'Malam Krismas. Cuti negeri di Sabah.',
    'christmas' => 'Hari Krismas pada 25 Disember. Cuti umum persekutuan di seluruh Malaysia.',
    'valentine' => 'Hari Valentine, hari pemerhatian antarabangsa untuk kasih sayang. Bukan cuti umum.',
    'chap_goh_mei' => 'Chap Goh Mei, hari ke-15 Tahun Baharu Cina. Pemerhatian budaya, bukan cuti umum.',
    'womens_day' => 'Hari Wanita Antarabangsa pada 8 Mac. Pemerhatian, bukan cuti umum.',
    'qing_ming' => 'Festival Qing Ming, hari menghormati nenek moyang. Pemerhatian budaya Cina.',
    'mothers_day' => 'Hari Ibu, Ahad kedua bulan Mei. Pemerhatian, bukan cuti umum.',
    'teachers_day' => 'Hari Guru Malaysia pada 16 Mei. Pemerhatian pendidikan, bukan cuti umum.',
    'fathers_day' => 'Hari Bapa, Ahad ketiga bulan Jun. Pemerhatian, bukan cuti umum.',
    'dragon_boat' => 'Festival Perahu Naga (Duanwu). Pemerhatian budaya Cina.',
    'hungry_ghost' => 'Festival Hungry Ghost / Zhongyuan. Pemerhatian budaya Cina.',
    'mid_autumn' => 'Festival Pertengahan Musim Luruh. Pemerhatian budaya Cina dengan kuih bulan.',
    'halloween' => 'Halloween pada 31 Oktober. Pemerhatian popular, bukan cuti umum Malaysia.',
    'nye' => 'Malam Tahun Baharu pada 31 Disember. Pemerhatian, bukan cuti umum.',
];
