-- Cuti MY full database dump
-- Import this file in phpMyAdmin (Select DB → Import).
-- Contains table structure + 2024-2026 holiday rows.
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS holidays;
CREATE TABLE IF NOT EXISTS holidays (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    holiday_date DATE NOT NULL,
    year SMALLINT UNSIGNED NOT NULL,
    name_en VARCHAR(160) NOT NULL,
    name_zh VARCHAR(160) NOT NULL,
    name_ms VARCHAR(160) NOT NULL,
    type ENUM('federal', 'state', 'observance') NOT NULL,
    states VARCHAR(255) DEFAULT NULL,
    description_en VARCHAR(500) DEFAULT NULL,
    description_zh VARCHAR(500) DEFAULT NULL,
    description_ms VARCHAR(500) DEFAULT NULL,
    is_birthday TINYINT(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY unique_holiday (holiday_date, name_en),
    INDEX idx_year (year),
    INDEX idx_holiday_date (holiday_date),
    INDEX idx_type (type),
    INDEX idx_is_birthday (is_birthday),
    INDEX idx_year_type (year, type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-01-01', 2024, 'New Year''s Day', '元旦', 'Hari Tahun Baharu', 'state', 'Melaka, Negeri Sembilan, Pahang, Pulau Pinang, Perak, Sabah, Sarawak, Selangor, Kuala Lumpur, Labuan, Putrajaya', 'Marks the first day of the Gregorian calendar. Observed as a public holiday in most states, but not in Johor, Kedah, Kelantan, Perlis and Terengganu.', '公历新年第一天。多数州属放假，但柔佛、吉打、吉兰丹、玻璃市与登嘉楼不放假。', 'Hari pertama kalendar Gregory. Cuti umum di kebanyakan negeri, kecuali Johor, Kedah, Kelantan, Perlis dan Terengganu.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-01-01', 2025, 'New Year''s Day', '元旦', 'Hari Tahun Baharu', 'state', 'Melaka, Negeri Sembilan, Pahang, Pulau Pinang, Perak, Sabah, Sarawak, Selangor, Kuala Lumpur, Labuan, Putrajaya', 'Marks the first day of the Gregorian calendar. Observed as a public holiday in most states, but not in Johor, Kedah, Kelantan, Perlis and Terengganu.', '公历新年第一天。多数州属放假，但柔佛、吉打、吉兰丹、玻璃市与登嘉楼不放假。', 'Hari pertama kalendar Gregory. Cuti umum di kebanyakan negeri, kecuali Johor, Kedah, Kelantan, Perlis dan Terengganu.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-01-01', 2026, 'New Year''s Day', '元旦', 'Hari Tahun Baharu', 'state', 'Melaka, Negeri Sembilan, Pahang, Pulau Pinang, Perak, Sabah, Sarawak, Selangor, Kuala Lumpur, Labuan, Putrajaya', 'Marks the first day of the Gregorian calendar. Observed as a public holiday in most states, but not in Johor, Kedah, Kelantan, Perlis and Terengganu.', '公历新年第一天。多数州属放假，但柔佛、吉打、吉兰丹、玻璃市与登嘉楼不放假。', 'Hari pertama kalendar Gregory. Cuti umum di kebanyakan negeri, kecuali Johor, Kedah, Kelantan, Perlis dan Terengganu.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-01-14', 2024, 'Birthday of the Yang di-Pertuan Besar of Negeri Sembilan', '森美兰州最高统治者华诞', 'Hari Keputeraan Yang di-Pertuan Besar Negeri Sembilan', 'state', 'Negeri Sembilan', 'Official birthday of the Yang di-Pertuan Besar of Negeri Sembilan. A state public holiday in Negeri Sembilan only.', '森美兰州最高统治者官方华诞，仅森美兰放假。', 'Hari keputeraan rasmi Yang di-Pertuan Besar Negeri Sembilan. Cuti negeri untuk Negeri Sembilan sahaja.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-01-14', 2025, 'Birthday of the Yang di-Pertuan Besar of Negeri Sembilan', '森美兰州最高统治者华诞', 'Hari Keputeraan Yang di-Pertuan Besar Negeri Sembilan', 'state', 'Negeri Sembilan', 'Official birthday of the Yang di-Pertuan Besar of Negeri Sembilan. A state public holiday in Negeri Sembilan only.', '森美兰州最高统治者官方华诞，仅森美兰放假。', 'Hari keputeraan rasmi Yang di-Pertuan Besar Negeri Sembilan. Cuti negeri untuk Negeri Sembilan sahaja.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-01-14', 2026, 'Birthday of the Yang di-Pertuan Besar of Negeri Sembilan', '森美兰州最高统治者华诞', 'Hari Keputeraan Yang di-Pertuan Besar Negeri Sembilan', 'state', 'Negeri Sembilan', 'Official birthday of the Yang di-Pertuan Besar of Negeri Sembilan. A state public holiday in Negeri Sembilan only.', '森美兰州最高统治者官方华诞，仅森美兰放假。', 'Hari keputeraan rasmi Yang di-Pertuan Besar Negeri Sembilan. Cuti negeri untuk Negeri Sembilan sahaja.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-01-25', 2024, 'Thaipusam', '大宝森节', 'Hari Thaipusam', 'state', 'Johor, Negeri Sembilan, Pulau Pinang, Perak, Selangor, Kuala Lumpur, Putrajaya', 'Hindu festival honouring Lord Murugan. A public holiday in Johor, Negeri Sembilan, Pulau Pinang, Perak, Selangor, Kuala Lumpur and Putrajaya.', '印度教大宝森节。柔佛、森美兰、槟城、霹雳、雪兰莪、吉隆坡与布城放假。', 'Perayaan Hindu sempena perjalanan Lord Murugan. Cuti di Johor, Negeri Sembilan, Pulau Pinang, Perak, Selangor, Kuala Lumpur dan Putrajaya.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-02-11', 2025, 'Thaipusam', '大宝森节', 'Hari Thaipusam', 'state', 'Johor, Negeri Sembilan, Pulau Pinang, Perak, Selangor, Kuala Lumpur, Putrajaya', 'Hindu festival honouring Lord Murugan. A public holiday in Johor, Negeri Sembilan, Pulau Pinang, Perak, Selangor, Kuala Lumpur and Putrajaya.', '印度教大宝森节。柔佛、森美兰、槟城、霹雳、雪兰莪、吉隆坡与布城放假。', 'Perayaan Hindu sempena perjalanan Lord Murugan. Cuti di Johor, Negeri Sembilan, Pulau Pinang, Perak, Selangor, Kuala Lumpur dan Putrajaya.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-02-01', 2026, 'Thaipusam', '大宝森节', 'Hari Thaipusam', 'state', 'Johor, Negeri Sembilan, Pulau Pinang, Perak, Selangor, Kuala Lumpur, Putrajaya', 'Hindu festival honouring Lord Murugan. A public holiday in Johor, Negeri Sembilan, Pulau Pinang, Perak, Selangor, Kuala Lumpur and Putrajaya.', '印度教大宝森节。柔佛、森美兰、槟城、霹雳、雪兰莪、吉隆坡与布城放假。', 'Perayaan Hindu sempena perjalanan Lord Murugan. Cuti di Johor, Negeri Sembilan, Pulau Pinang, Perak, Selangor, Kuala Lumpur dan Putrajaya.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-02-08', 2024, 'Israk and Mikraj', '夜行登霄', 'Israk dan Mikraj', 'state', 'Kedah, Negeri Sembilan, Perlis, Terengganu', 'Commemorates the Prophet Muhammad''s night journey. A public holiday in Kedah, Negeri Sembilan, Perlis and Terengganu.', '纪念先知穆罕默德夜行登霄。吉打、森美兰、玻璃市与登嘉楼放假。', 'Memperingati Israk dan Mikraj Nabi Muhammad. Cuti di Kedah, Negeri Sembilan, Perlis dan Terengganu.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-01-27', 2025, 'Israk and Mikraj', '夜行登霄', 'Israk dan Mikraj', 'state', 'Kedah, Negeri Sembilan, Perlis, Terengganu', 'Commemorates the Prophet Muhammad''s night journey. A public holiday in Kedah, Negeri Sembilan, Perlis and Terengganu.', '纪念先知穆罕默德夜行登霄。吉打、森美兰、玻璃市与登嘉楼放假。', 'Memperingati Israk dan Mikraj Nabi Muhammad. Cuti di Kedah, Negeri Sembilan, Perlis dan Terengganu.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-01-17', 2026, 'Israk and Mikraj', '夜行登霄', 'Israk dan Mikraj', 'state', 'Kedah, Negeri Sembilan, Perlis, Terengganu', 'Commemorates the Prophet Muhammad''s night journey. A public holiday in Kedah, Negeri Sembilan, Perlis and Terengganu.', '纪念先知穆罕默德夜行登霄。吉打、森美兰、玻璃市与登嘉楼放假。', 'Memperingati Israk dan Mikraj Nabi Muhammad. Cuti di Kedah, Negeri Sembilan, Perlis dan Terengganu.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-02-10', 2024, 'Chinese New Year', '农历新年', 'Tahun Baharu Cina', 'federal', NULL, 'First day of the Lunar New Year. A federal public holiday throughout Malaysia.', '农历正月初一，马来西亚全国联邦公共假期。', 'Hari pertama Tahun Baharu Cina mengikut kalendar lunar. Cuti umum persekutuan di seluruh Malaysia.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-01-29', 2025, 'Chinese New Year', '农历新年', 'Tahun Baharu Cina', 'federal', NULL, 'First day of the Lunar New Year. A federal public holiday throughout Malaysia.', '农历正月初一，马来西亚全国联邦公共假期。', 'Hari pertama Tahun Baharu Cina mengikut kalendar lunar. Cuti umum persekutuan di seluruh Malaysia.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-02-17', 2026, 'Chinese New Year', '农历新年', 'Tahun Baharu Cina', 'federal', NULL, 'First day of the Lunar New Year. A federal public holiday throughout Malaysia.', '农历正月初一，马来西亚全国联邦公共假期。', 'Hari pertama Tahun Baharu Cina mengikut kalendar lunar. Cuti umum persekutuan di seluruh Malaysia.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-02-11', 2024, 'Chinese New Year (Second Day)', '农历新年第二天', 'Tahun Baharu Cina (Hari Kedua)', 'federal', 'Johor, Kedah, Melaka, Negeri Sembilan, Pahang, Pulau Pinang, Perak, Perlis, Sabah, Sarawak, Selangor, Kuala Lumpur, Labuan, Putrajaya', 'Second day of the Lunar New Year. Observed nationwide except Kelantan and Terengganu.', '农历正月初二。全国放假，吉兰丹与登嘉楼除外。', 'Hari kedua Tahun Baharu Cina. Diperhatikan di seluruh negara kecuali Kelantan dan Terengganu.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-01-30', 2025, 'Chinese New Year (Second Day)', '农历新年第二天', 'Tahun Baharu Cina (Hari Kedua)', 'federal', 'Johor, Kedah, Melaka, Negeri Sembilan, Pahang, Pulau Pinang, Perak, Perlis, Sabah, Sarawak, Selangor, Kuala Lumpur, Labuan, Putrajaya', 'Second day of the Lunar New Year. Observed nationwide except Kelantan and Terengganu.', '农历正月初二。全国放假，吉兰丹与登嘉楼除外。', 'Hari kedua Tahun Baharu Cina. Diperhatikan di seluruh negara kecuali Kelantan dan Terengganu.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-02-18', 2026, 'Chinese New Year (Second Day)', '农历新年第二天', 'Tahun Baharu Cina (Hari Kedua)', 'federal', 'Johor, Kedah, Melaka, Negeri Sembilan, Pahang, Pulau Pinang, Perak, Perlis, Sabah, Sarawak, Selangor, Kuala Lumpur, Labuan, Putrajaya', 'Second day of the Lunar New Year. Observed nationwide except Kelantan and Terengganu.', '农历正月初二。全国放假，吉兰丹与登嘉楼除外。', 'Hari kedua Tahun Baharu Cina. Diperhatikan di seluruh negara kecuali Kelantan dan Terengganu.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-02-12', 2024, 'Chinese New Year (Replacement)', '农历新年（补假）', 'Tahun Baharu Cina (Cuti Ganti)', 'federal', 'Melaka, Negeri Sembilan, Pahang, Pulau Pinang, Perak, Sabah, Sarawak, Selangor, Kuala Lumpur, Labuan, Putrajaya', 'Replacement holiday when Chinese New Year falls on a weekend rest day.', '农历新年适逢周末休息日时的补假。', 'Cuti ganti Tahun Baharu Cina apabila hari perayaan jatuh pada hujung minggu.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-02-01', 2024, 'Federal Territory Day', '联邦直辖区日', 'Hari Wilayah Persekutuan', 'state', 'Kuala Lumpur, Labuan, Putrajaya', 'Commemorates the establishment of the Federal Territories. Observed in Kuala Lumpur, Labuan and Putrajaya.', '纪念联邦直辖区成立，吉隆坡、纳闽与布城放假。', 'Memperingati penubuhan Wilayah Persekutuan. Cuti di Kuala Lumpur, Labuan dan Putrajaya.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-02-01', 2025, 'Federal Territory Day', '联邦直辖区日', 'Hari Wilayah Persekutuan', 'state', 'Kuala Lumpur, Labuan, Putrajaya', 'Commemorates the establishment of the Federal Territories. Observed in Kuala Lumpur, Labuan and Putrajaya.', '纪念联邦直辖区成立，吉隆坡、纳闽与布城放假。', 'Memperingati penubuhan Wilayah Persekutuan. Cuti di Kuala Lumpur, Labuan dan Putrajaya.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-02-01', 2026, 'Federal Territory Day', '联邦直辖区日', 'Hari Wilayah Persekutuan', 'state', 'Kuala Lumpur, Labuan, Putrajaya', 'Commemorates the establishment of the Federal Territories. Observed in Kuala Lumpur, Labuan and Putrajaya.', '纪念联邦直辖区成立，吉隆坡、纳闽与布城放假。', 'Memperingati penubuhan Wilayah Persekutuan. Cuti di Kuala Lumpur, Labuan dan Putrajaya.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-02-20', 2024, 'Declaration of Independence Day (Melaka)', '马六甲独立宣言日', 'Hari Pengisytiharan Tarikh Kemerdekaan Melaka', 'state', 'Melaka', 'Commemorates Melaka''s declaration of independence. A state holiday in Melaka.', '纪念马六甲宣布独立日期，马六甲州假期。', 'Memperingati pengisytiharan tarikh kemerdekaan Melaka. Cuti negeri Melaka.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-02-20', 2025, 'Declaration of Independence Day (Melaka)', '马六甲独立宣言日', 'Hari Pengisytiharan Tarikh Kemerdekaan Melaka', 'state', 'Melaka', 'Commemorates Melaka''s declaration of independence. A state holiday in Melaka.', '纪念马六甲宣布独立日期，马六甲州假期。', 'Memperingati pengisytiharan tarikh kemerdekaan Melaka. Cuti negeri Melaka.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-02-20', 2026, 'Declaration of Independence Day (Melaka)', '马六甲独立宣言日', 'Hari Pengisytiharan Tarikh Kemerdekaan Melaka', 'state', 'Melaka', 'Commemorates Melaka''s declaration of independence. A state holiday in Melaka.', '纪念马六甲宣布独立日期，马六甲州假期。', 'Memperingati pengisytiharan tarikh kemerdekaan Melaka. Cuti negeri Melaka.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-03-12', 2024, 'Awal Ramadan', '斋月首日', 'Awal Ramadan', 'state', 'Johor, Kedah', 'First day of the fasting month of Ramadan. A public holiday in Johor and Kedah.', '斋月第一天，柔佛与吉打放假。', 'Hari pertama bulan Ramadan. Cuti di Johor dan Kedah.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-03-02', 2025, 'Awal Ramadan', '斋月首日', 'Awal Ramadan', 'state', 'Johor, Kedah', 'First day of the fasting month of Ramadan. A public holiday in Johor and Kedah.', '斋月第一天，柔佛与吉打放假。', 'Hari pertama bulan Ramadan. Cuti di Johor dan Kedah.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-02-19', 2026, 'Awal Ramadan', '斋月首日', 'Awal Ramadan', 'state', 'Johor, Kedah', 'First day of the fasting month of Ramadan. A public holiday in Johor and Kedah.', '斋月第一天，柔佛与吉打放假。', 'Hari pertama bulan Ramadan. Cuti di Johor dan Kedah.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-03-03', 2025, 'Awal Ramadan Holiday (Johor)', '斋月首日（柔佛补假）', 'Cuti Awal Ramadan (Johor)', 'state', 'Johor', 'Additional Johor holiday when Awal Ramadan falls on the state weekend.', '斋月首日适逢柔佛周末时的额外假期。', 'Cuti tambahan Johor sempena Awal Ramadan yang jatuh pada hujung minggu negeri.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-03-04', 2024, 'Anniversary of the Installation of the Sultan of Terengganu', '登嘉楼苏丹登基纪念日', 'Ulang Tahun Pertabalan Sultan Terengganu', 'state', 'Terengganu', 'Anniversary of the installation of the Sultan of Terengganu. A state holiday in Terengganu.', '登嘉楼苏丹登基周年纪念，登嘉楼州假期。', 'Ulang tahun pertabalan Sultan Terengganu. Cuti negeri Terengganu.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-03-04', 2025, 'Anniversary of the Installation of the Sultan of Terengganu', '登嘉楼苏丹登基纪念日', 'Ulang Tahun Pertabalan Sultan Terengganu', 'state', 'Terengganu', 'Anniversary of the installation of the Sultan of Terengganu. A state holiday in Terengganu.', '登嘉楼苏丹登基周年纪念，登嘉楼州假期。', 'Ulang tahun pertabalan Sultan Terengganu. Cuti negeri Terengganu.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-03-04', 2026, 'Anniversary of the Installation of the Sultan of Terengganu', '登嘉楼苏丹登基纪念日', 'Ulang Tahun Pertabalan Sultan Terengganu', 'state', 'Terengganu', 'Anniversary of the installation of the Sultan of Terengganu. A state holiday in Terengganu.', '登嘉楼苏丹登基周年纪念，登嘉楼州假期。', 'Ulang tahun pertabalan Sultan Terengganu. Cuti negeri Terengganu.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-03-28', 2024, 'Nuzul Al-Quran', '古兰经降临日', 'Hari Nuzul Al-Quran', 'state', 'Kelantan, Pahang, Pulau Pinang, Perak, Perlis, Selangor, Terengganu, Kuala Lumpur, Labuan, Putrajaya', 'Commemorates the revelation of the Quran. Observed in several Peninsular states and the Federal Territories.', '纪念《古兰经》降临。若干半岛州属与联邦直辖区放假。', 'Memperingati penurunan Al-Quran. Cuti di beberapa negeri Semenanjung dan Wilayah Persekutuan.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-03-18', 2025, 'Nuzul Al-Quran', '古兰经降临日', 'Hari Nuzul Al-Quran', 'state', 'Kelantan, Pahang, Pulau Pinang, Perak, Perlis, Selangor, Terengganu, Kuala Lumpur, Labuan, Putrajaya', 'Commemorates the revelation of the Quran. Observed in several Peninsular states and the Federal Territories.', '纪念《古兰经》降临。若干半岛州属与联邦直辖区放假。', 'Memperingati penurunan Al-Quran. Cuti di beberapa negeri Semenanjung dan Wilayah Persekutuan.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-03-07', 2026, 'Nuzul Al-Quran', '古兰经降临日', 'Hari Nuzul Al-Quran', 'state', 'Kelantan, Pahang, Pulau Pinang, Perak, Perlis, Selangor, Terengganu, Kuala Lumpur, Labuan, Putrajaya', 'Commemorates the revelation of the Quran. Observed in several Peninsular states and the Federal Territories.', '纪念《古兰经》降临。若干半岛州属与联邦直辖区放假。', 'Memperingati penurunan Al-Quran. Cuti di beberapa negeri Semenanjung dan Wilayah Persekutuan.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-03-23', 2024, 'Birthday of the Sultan of Johor', '柔佛苏丹华诞', 'Hari Keputeraan Sultan Johor', 'state', 'Johor', 'Official birthday of the Sultan of Johor, held on 23 March each year. A state holiday in Johor.', '柔佛苏丹官方华诞，每年3月23日，仅柔佛放假。', 'Hari keputeraan rasmi Sultan Johor pada 23 Mac setiap tahun. Cuti negeri Johor.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-03-23', 2025, 'Birthday of the Sultan of Johor', '柔佛苏丹华诞', 'Hari Keputeraan Sultan Johor', 'state', 'Johor', 'Official birthday of the Sultan of Johor, held on 23 March each year. A state holiday in Johor.', '柔佛苏丹官方华诞，每年3月23日，仅柔佛放假。', 'Hari keputeraan rasmi Sultan Johor pada 23 Mac setiap tahun. Cuti negeri Johor.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-03-23', 2026, 'Birthday of the Sultan of Johor', '柔佛苏丹华诞', 'Hari Keputeraan Sultan Johor', 'state', 'Johor', 'Official birthday of the Sultan of Johor, held on 23 March each year. A state holiday in Johor.', '柔佛苏丹官方华诞，每年3月23日，仅柔佛放假。', 'Hari keputeraan rasmi Sultan Johor pada 23 Mac setiap tahun. Cuti negeri Johor.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-04-10', 2024, 'Hari Raya Aidilfitri', '开斋节', 'Hari Raya Aidilfitri', 'federal', NULL, 'First day of Hari Raya Aidilfitri, marking the end of Ramadan. A federal public holiday nationwide.', '开斋节第一天，斋月结束。全国联邦公共假期。', 'Hari pertama Aidilfitri, merayakan berakhirnya Ramadan. Cuti umum persekutuan di seluruh Malaysia.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-03-31', 2025, 'Hari Raya Aidilfitri', '开斋节', 'Hari Raya Aidilfitri', 'federal', NULL, 'First day of Hari Raya Aidilfitri, marking the end of Ramadan. A federal public holiday nationwide.', '开斋节第一天，斋月结束。全国联邦公共假期。', 'Hari pertama Aidilfitri, merayakan berakhirnya Ramadan. Cuti umum persekutuan di seluruh Malaysia.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-03-21', 2026, 'Hari Raya Aidilfitri', '开斋节', 'Hari Raya Aidilfitri', 'federal', NULL, 'First day of Hari Raya Aidilfitri, marking the end of Ramadan. A federal public holiday nationwide.', '开斋节第一天，斋月结束。全国联邦公共假期。', 'Hari pertama Aidilfitri, merayakan berakhirnya Ramadan. Cuti umum persekutuan di seluruh Malaysia.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-04-11', 2024, 'Hari Raya Aidilfitri (Second Day)', '开斋节第二天', 'Hari Raya Aidilfitri (Hari Kedua)', 'federal', NULL, 'Second day of Hari Raya Aidilfitri. A federal public holiday nationwide.', '开斋节第二天，全国联邦公共假期。', 'Hari kedua Aidilfitri. Cuti umum persekutuan di seluruh Malaysia.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-04-01', 2025, 'Hari Raya Aidilfitri (Second Day)', '开斋节第二天', 'Hari Raya Aidilfitri (Hari Kedua)', 'federal', NULL, 'Second day of Hari Raya Aidilfitri. A federal public holiday nationwide.', '开斋节第二天，全国联邦公共假期。', 'Hari kedua Aidilfitri. Cuti umum persekutuan di seluruh Malaysia.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-03-22', 2026, 'Hari Raya Aidilfitri (Second Day)', '开斋节第二天', 'Hari Raya Aidilfitri (Hari Kedua)', 'federal', NULL, 'Second day of Hari Raya Aidilfitri. A federal public holiday nationwide.', '开斋节第二天，全国联邦公共假期。', 'Hari kedua Aidilfitri. Cuti umum persekutuan di seluruh Malaysia.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-04-02', 2025, 'Hari Raya Aidilfitri (Third Day)', '开斋节第三天', 'Hari Raya Aidilfitri (Hari Ketiga)', 'state', 'Melaka', 'Additional Melaka holiday linked to Hari Raya Aidilfitri.', '马六甲开斋节额外假期。', 'Cuti tambahan Melaka sempena Aidilfitri.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-03-23', 2026, 'Hari Raya Aidilfitri (Third Day)', '开斋节第三天', 'Hari Raya Aidilfitri (Hari Ketiga)', 'state', 'Melaka', 'Additional Melaka holiday linked to Hari Raya Aidilfitri.', '马六甲开斋节额外假期。', 'Cuti tambahan Melaka sempena Aidilfitri.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-03-29', 2024, 'Good Friday', '耶稣受难日', 'Good Friday', 'state', 'Sabah, Sarawak', 'Christian holy day observed as a public holiday in Sabah and Sarawak.', '基督教耶稣受难日，沙巴与砂拉越放假。', 'Good Friday dalam kalendar Kristian. Cuti di Sabah dan Sarawak.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-04-18', 2025, 'Good Friday', '耶稣受难日', 'Good Friday', 'state', 'Sabah, Sarawak', 'Christian holy day observed as a public holiday in Sabah and Sarawak.', '基督教耶稣受难日，沙巴与砂拉越放假。', 'Good Friday dalam kalendar Kristian. Cuti di Sabah dan Sarawak.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-04-03', 2026, 'Good Friday', '耶稣受难日', 'Good Friday', 'state', 'Sabah, Sarawak', 'Christian holy day observed as a public holiday in Sabah and Sarawak.', '基督教耶稣受难日，沙巴与砂拉越放假。', 'Good Friday dalam kalendar Kristian. Cuti di Sabah dan Sarawak.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-04-15', 2024, 'Declaration of Melaka as a Historical City', '马六甲历史城市宣言日', 'Hari Pengisytiharan Melaka sebagai Bandaraya Bersejarah', 'state', 'Melaka', 'Commemorates the declaration of Melaka as a Historical City. A state holiday in Melaka.', '纪念马六甲获宣布为历史城市，马六甲州假期。', 'Memperingati pengisytiharan Melaka sebagai Bandaraya Bersejarah. Cuti negeri Melaka.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-04-15', 2025, 'Declaration of Melaka as a Historical City', '马六甲历史城市宣言日', 'Hari Pengisytiharan Melaka sebagai Bandaraya Bersejarah', 'state', 'Melaka', 'Commemorates the declaration of Melaka as a Historical City. A state holiday in Melaka.', '纪念马六甲获宣布为历史城市，马六甲州假期。', 'Memperingati pengisytiharan Melaka sebagai Bandaraya Bersejarah. Cuti negeri Melaka.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-04-26', 2024, 'Birthday of the Sultan of Terengganu', '登嘉楼苏丹华诞', 'Hari Keputeraan Sultan Terengganu', 'state', 'Terengganu', 'Official birthday of the Sultan of Terengganu on 26 April. A state holiday in Terengganu.', '登嘉楼苏丹官方华诞，每年4月26日。', 'Hari keputeraan rasmi Sultan Terengganu pada 26 April. Cuti negeri Terengganu.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-04-26', 2025, 'Birthday of the Sultan of Terengganu', '登嘉楼苏丹华诞', 'Hari Keputeraan Sultan Terengganu', 'state', 'Terengganu', 'Official birthday of the Sultan of Terengganu on 26 April. A state holiday in Terengganu.', '登嘉楼苏丹官方华诞，每年4月26日。', 'Hari keputeraan rasmi Sultan Terengganu pada 26 April. Cuti negeri Terengganu.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-04-26', 2026, 'Birthday of the Sultan of Terengganu', '登嘉楼苏丹华诞', 'Hari Keputeraan Sultan Terengganu', 'state', 'Terengganu', 'Official birthday of the Sultan of Terengganu on 26 April. A state holiday in Terengganu.', '登嘉楼苏丹官方华诞，每年4月26日。', 'Hari keputeraan rasmi Sultan Terengganu pada 26 April. Cuti negeri Terengganu.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-05-01', 2024, 'Labour Day', '劳动节', 'Hari Pekerja', 'federal', NULL, 'Labour Day is a federal public holiday on 1 May throughout Malaysia.', '劳动节，每年5月1日全国联邦公共假期。', 'Hari Pekerja, cuti umum persekutuan pada 1 Mei di seluruh Malaysia.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-05-01', 2025, 'Labour Day', '劳动节', 'Hari Pekerja', 'federal', NULL, 'Labour Day is a federal public holiday on 1 May throughout Malaysia.', '劳动节，每年5月1日全国联邦公共假期。', 'Hari Pekerja, cuti umum persekutuan pada 1 Mei di seluruh Malaysia.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-05-01', 2026, 'Labour Day', '劳动节', 'Hari Pekerja', 'federal', NULL, 'Labour Day is a federal public holiday on 1 May throughout Malaysia.', '劳动节，每年5月1日全国联邦公共假期。', 'Hari Pekerja, cuti umum persekutuan pada 1 Mei di seluruh Malaysia.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-05-22', 2024, 'Wesak Day', '卫塞节', 'Hari Wesak', 'federal', NULL, 'Wesak Day commemorates the birth, enlightenment and passing of Buddha. A federal public holiday.', '卫塞节纪念佛陀诞生、成道与涅槃，全国联邦公共假期。', 'Hari Wesak, memperingati kelahiran, tercerah dan parinirvana Buddha. Cuti umum persekutuan.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-05-12', 2025, 'Wesak Day', '卫塞节', 'Hari Wesak', 'federal', NULL, 'Wesak Day commemorates the birth, enlightenment and passing of Buddha. A federal public holiday.', '卫塞节纪念佛陀诞生、成道与涅槃，全国联邦公共假期。', 'Hari Wesak, memperingati kelahiran, tercerah dan parinirvana Buddha. Cuti umum persekutuan.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-05-31', 2026, 'Wesak Day', '卫塞节', 'Hari Wesak', 'federal', NULL, 'Wesak Day commemorates the birth, enlightenment and passing of Buddha. A federal public holiday.', '卫塞节纪念佛陀诞生、成道与涅槃，全国联邦公共假期。', 'Hari Wesak, memperingati kelahiran, tercerah dan parinirvana Buddha. Cuti umum persekutuan.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-06-02', 2026, 'Wesak Day (Replacement)', '卫塞节（补假）', 'Hari Wesak (Cuti Ganti)', 'federal', NULL, 'Replacement holiday when Wesak Day falls on a rest day or coincides with another holiday.', '卫塞节适逢休息日或与其他假期重叠时的补假。', 'Cuti ganti Hari Wesak apabila tarikh rasmi jatuh pada hujung minggu atau bercantum dengan cuti lain.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-05-17', 2024, 'Birthday of the Raja of Perlis', '玻璃市拉惹华诞', 'Hari Keputeraan Raja Perlis', 'state', 'Perlis', 'Birthday of the Raja of Perlis on 17 May. A state holiday in Perlis.', '玻璃市拉惹华诞，每年5月17日，仅玻璃市放假。', 'Hari keputeraan Raja Perlis pada 17 Mei. Cuti negeri Perlis.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-05-17', 2025, 'Birthday of the Raja of Perlis', '玻璃市拉惹华诞', 'Hari Keputeraan Raja Perlis', 'state', 'Perlis', 'Birthday of the Raja of Perlis on 17 May. A state holiday in Perlis.', '玻璃市拉惹华诞，每年5月17日，仅玻璃市放假。', 'Hari keputeraan Raja Perlis pada 17 Mei. Cuti negeri Perlis.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-05-17', 2026, 'Birthday of the Raja of Perlis', '玻璃市拉惹华诞', 'Hari Keputeraan Raja Perlis', 'state', 'Perlis', 'Birthday of the Raja of Perlis on 17 May. A state holiday in Perlis.', '玻璃市拉惹华诞，每年5月17日，仅玻璃市放假。', 'Hari keputeraan Raja Perlis pada 17 Mei. Cuti negeri Perlis.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-05-07', 2024, 'Pahang Hol Day', '彭亨王室忌辰', 'Hari Hol Pahang', 'state', 'Pahang', 'Pahang Hol Day commemorates a late Sultan of Pahang. A state holiday in Pahang.', '彭亨王室忌辰，仅彭亨放假。', 'Hari Hol Almarhum Sultan Pahang. Cuti negeri Pahang.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-05-22', 2025, 'Pahang Hol Day', '彭亨王室忌辰', 'Hari Hol Pahang', 'state', 'Pahang', 'Pahang Hol Day commemorates a late Sultan of Pahang. A state holiday in Pahang.', '彭亨王室忌辰，仅彭亨放假。', 'Hari Hol Almarhum Sultan Pahang. Cuti negeri Pahang.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-05-22', 2026, 'Pahang Hol Day', '彭亨王室忌辰', 'Hari Hol Pahang', 'state', 'Pahang', 'Pahang Hol Day commemorates a late Sultan of Pahang. A state holiday in Pahang.', '彭亨王室忌辰，仅彭亨放假。', 'Hari Hol Almarhum Sultan Pahang. Cuti negeri Pahang.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-06-16', 2024, 'Arafah Day', '阿拉法日', 'Hari Arafah', 'state', 'Kelantan, Terengganu', 'Arafah Day, the day before Hari Raya Aidiladha. A public holiday in Kelantan and Terengganu.', '阿拉法日，哈芝节前一天。吉兰丹与登嘉楼放假。', 'Hari Arafah, sehari sebelum Aidiladha. Cuti di Kelantan dan Terengganu.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-06-06', 2025, 'Arafah Day', '阿拉法日', 'Hari Arafah', 'state', 'Kelantan, Terengganu', 'Arafah Day, the day before Hari Raya Aidiladha. A public holiday in Kelantan and Terengganu.', '阿拉法日，哈芝节前一天。吉兰丹与登嘉楼放假。', 'Hari Arafah, sehari sebelum Aidiladha. Cuti di Kelantan dan Terengganu.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-05-26', 2026, 'Arafah Day', '阿拉法日', 'Hari Arafah', 'state', 'Kelantan, Terengganu', 'Arafah Day, the day before Hari Raya Aidiladha. A public holiday in Kelantan and Terengganu.', '阿拉法日，哈芝节前一天。吉兰丹与登嘉楼放假。', 'Hari Arafah, sehari sebelum Aidiladha. Cuti di Kelantan dan Terengganu.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-06-17', 2024, 'Hari Raya Aidiladha', '哈芝节', 'Hari Raya Aidiladha', 'federal', NULL, 'Hari Raya Aidiladha commemorates the sacrifice of Prophet Ibrahim. A federal public holiday.', '哈芝节纪念先知易卜拉欣的奉献，全国联邦公共假期。', 'Hari Raya Aidiladha, memperingati pengorbanan Nabi Ibrahim. Cuti umum persekutuan.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-06-07', 2025, 'Hari Raya Aidiladha', '哈芝节', 'Hari Raya Aidiladha', 'federal', NULL, 'Hari Raya Aidiladha commemorates the sacrifice of Prophet Ibrahim. A federal public holiday.', '哈芝节纪念先知易卜拉欣的奉献，全国联邦公共假期。', 'Hari Raya Aidiladha, memperingati pengorbanan Nabi Ibrahim. Cuti umum persekutuan.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-05-27', 2026, 'Hari Raya Aidiladha', '哈芝节', 'Hari Raya Aidiladha', 'federal', NULL, 'Hari Raya Aidiladha commemorates the sacrifice of Prophet Ibrahim. A federal public holiday.', '哈芝节纪念先知易卜拉欣的奉献，全国联邦公共假期。', 'Hari Raya Aidiladha, memperingati pengorbanan Nabi Ibrahim. Cuti umum persekutuan.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-06-18', 2024, 'Hari Raya Aidiladha (Second Day)', '哈芝节第二天', 'Hari Raya Aidiladha (Hari Kedua)', 'state', 'Kedah, Kelantan, Perlis, Terengganu', 'Second day of Hari Raya Aidiladha. Observed in Kedah, Kelantan, Perlis and Terengganu.', '哈芝节第二天。吉打、吉兰丹、玻璃市与登嘉楼放假。', 'Hari kedua Aidiladha. Cuti di Kedah, Kelantan, Perlis dan Terengganu.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-06-08', 2025, 'Hari Raya Aidiladha (Second Day)', '哈芝节第二天', 'Hari Raya Aidiladha (Hari Kedua)', 'state', 'Kedah, Kelantan, Perlis, Terengganu', 'Second day of Hari Raya Aidiladha. Observed in Kedah, Kelantan, Perlis and Terengganu.', '哈芝节第二天。吉打、吉兰丹、玻璃市与登嘉楼放假。', 'Hari kedua Aidiladha. Cuti di Kedah, Kelantan, Perlis dan Terengganu.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-05-28', 2026, 'Hari Raya Aidiladha (Second Day)', '哈芝节第二天', 'Hari Raya Aidiladha (Hari Kedua)', 'state', 'Kedah, Kelantan, Perlis, Terengganu', 'Second day of Hari Raya Aidiladha. Observed in Kedah, Kelantan, Perlis and Terengganu.', '哈芝节第二天。吉打、吉兰丹、玻璃市与登嘉楼放假。', 'Hari kedua Aidiladha. Cuti di Kedah, Kelantan, Perlis dan Terengganu.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-05-30', 2024, 'Pesta Kaamatan', '丰收节（第一天）', 'Pesta Kaamatan', 'state', 'Sabah, Labuan', 'Kaamatan is the harvest festival of the Kadazan-Dusun community. A holiday in Sabah and Labuan.', '卡达山杜顺族丰收节，沙巴与纳闽放假。', 'Pesta Kaamatan, perayaan menuai Kadazan-Dusun. Cuti di Sabah dan Labuan.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-05-30', 2025, 'Pesta Kaamatan', '丰收节（第一天）', 'Pesta Kaamatan', 'state', 'Sabah, Labuan', 'Kaamatan is the harvest festival of the Kadazan-Dusun community. A holiday in Sabah and Labuan.', '卡达山杜顺族丰收节，沙巴与纳闽放假。', 'Pesta Kaamatan, perayaan menuai Kadazan-Dusun. Cuti di Sabah dan Labuan.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-05-30', 2026, 'Pesta Kaamatan', '丰收节（第一天）', 'Pesta Kaamatan', 'state', 'Sabah, Labuan', 'Kaamatan is the harvest festival of the Kadazan-Dusun community. A holiday in Sabah and Labuan.', '卡达山杜顺族丰收节，沙巴与纳闽放假。', 'Pesta Kaamatan, perayaan menuai Kadazan-Dusun. Cuti di Sabah dan Labuan.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-05-31', 2024, 'Pesta Kaamatan (Second Day)', '丰收节（第二天）', 'Pesta Kaamatan (Hari Kedua)', 'state', 'Sabah, Labuan', 'Second day of the Kaamatan harvest festival in Sabah and Labuan.', '丰收节第二天，沙巴与纳闽放假。', 'Hari kedua Pesta Kaamatan di Sabah dan Labuan.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-05-31', 2025, 'Pesta Kaamatan (Second Day)', '丰收节（第二天）', 'Pesta Kaamatan (Hari Kedua)', 'state', 'Sabah, Labuan', 'Second day of the Kaamatan harvest festival in Sabah and Labuan.', '丰收节第二天，沙巴与纳闽放假。', 'Hari kedua Pesta Kaamatan di Sabah dan Labuan.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-05-31', 2026, 'Pesta Kaamatan (Second Day)', '丰收节（第二天）', 'Pesta Kaamatan (Hari Kedua)', 'state', 'Sabah, Labuan', 'Second day of the Kaamatan harvest festival in Sabah and Labuan.', '丰收节第二天，沙巴与纳闽放假。', 'Hari kedua Pesta Kaamatan di Sabah dan Labuan.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-06-01', 2024, 'Gawai Dayak', '加瓦伊节', 'Hari Gawai Dayak', 'state', 'Sarawak', 'Gawai Dayak is the harvest festival of the Dayak community. A state holiday in Sarawak.', '达雅族加瓦伊丰收节，砂拉越州假期。', 'Hari Gawai Dayak, perayaan menuai komuniti Dayak. Cuti negeri Sarawak.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-06-01', 2025, 'Gawai Dayak', '加瓦伊节', 'Hari Gawai Dayak', 'state', 'Sarawak', 'Gawai Dayak is the harvest festival of the Dayak community. A state holiday in Sarawak.', '达雅族加瓦伊丰收节，砂拉越州假期。', 'Hari Gawai Dayak, perayaan menuai komuniti Dayak. Cuti negeri Sarawak.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-06-01', 2026, 'Gawai Dayak', '加瓦伊节', 'Hari Gawai Dayak', 'state', 'Sarawak', 'Gawai Dayak is the harvest festival of the Dayak community. A state holiday in Sarawak.', '达雅族加瓦伊丰收节，砂拉越州假期。', 'Hari Gawai Dayak, perayaan menuai komuniti Dayak. Cuti negeri Sarawak.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-06-02', 2024, 'Gawai Dayak (Second Day)', '加瓦伊节第二天', 'Hari Gawai Dayak (Hari Kedua)', 'state', 'Sarawak', 'Second day of Gawai Dayak in Sarawak.', '加瓦伊节第二天，砂拉越放假。', 'Hari kedua Gawai Dayak di Sarawak.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-06-02', 2025, 'Gawai Dayak (Second Day)', '加瓦伊节第二天', 'Hari Gawai Dayak (Hari Kedua)', 'state', 'Sarawak', 'Second day of Gawai Dayak in Sarawak.', '加瓦伊节第二天，砂拉越放假。', 'Hari kedua Gawai Dayak di Sarawak.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-06-02', 2026, 'Gawai Dayak (Second Day)', '加瓦伊节第二天', 'Hari Gawai Dayak (Hari Kedua)', 'state', 'Sarawak', 'Second day of Gawai Dayak in Sarawak.', '加瓦伊节第二天，砂拉越放假。', 'Hari kedua Gawai Dayak di Sarawak.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-06-03', 2024, 'Yang di-Pertuan Agong''s Birthday', '最高元首华诞', 'Hari Keputeraan Yang di-Pertuan Agong', 'federal', NULL, 'Official birthday of the Yang di-Pertuan Agong. A federal public holiday throughout Malaysia.', '马来西亚最高元首官方华诞，全国联邦公共假期。', 'Hari keputeraan rasmi Yang di-Pertuan Agong. Cuti umum persekutuan di seluruh Malaysia.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-06-02', 2025, 'Yang di-Pertuan Agong''s Birthday', '最高元首华诞', 'Hari Keputeraan Yang di-Pertuan Agong', 'federal', NULL, 'Official birthday of the Yang di-Pertuan Agong. A federal public holiday throughout Malaysia.', '马来西亚最高元首官方华诞，全国联邦公共假期。', 'Hari keputeraan rasmi Yang di-Pertuan Agong. Cuti umum persekutuan di seluruh Malaysia.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-06-01', 2026, 'Yang di-Pertuan Agong''s Birthday', '最高元首华诞', 'Hari Keputeraan Yang di-Pertuan Agong', 'federal', NULL, 'Official birthday of the Yang di-Pertuan Agong. A federal public holiday throughout Malaysia.', '马来西亚最高元首官方华诞，全国联邦公共假期。', 'Hari keputeraan rasmi Yang di-Pertuan Agong. Cuti umum persekutuan di seluruh Malaysia.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-07-07', 2024, 'Awal Muharram (Maal Hijrah)', '伊斯兰新年', 'Awal Muharam (Maal Hijrah)', 'federal', NULL, 'Islamic New Year (Maal Hijrah). A federal public holiday nationwide.', '伊斯兰历新年（迁徙纪念日），全国联邦公共假期。', 'Awal Muharam / Maal Hijrah, tahun baharu Islam. Cuti umum persekutuan.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-06-27', 2025, 'Awal Muharram (Maal Hijrah)', '伊斯兰新年', 'Awal Muharam (Maal Hijrah)', 'federal', NULL, 'Islamic New Year (Maal Hijrah). A federal public holiday nationwide.', '伊斯兰历新年（迁徙纪念日），全国联邦公共假期。', 'Awal Muharam / Maal Hijrah, tahun baharu Islam. Cuti umum persekutuan.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-06-17', 2026, 'Awal Muharram (Maal Hijrah)', '伊斯兰新年', 'Awal Muharam (Maal Hijrah)', 'federal', NULL, 'Islamic New Year (Maal Hijrah). A federal public holiday nationwide.', '伊斯兰历新年（迁徙纪念日），全国联邦公共假期。', 'Awal Muharam / Maal Hijrah, tahun baharu Islam. Cuti umum persekutuan.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-06-30', 2024, 'Birthday of the Sultan of Kedah', '吉打苏丹华诞', 'Hari Keputeraan Sultan Kedah', 'state', 'Kedah', 'Official birthday of the Sultan of Kedah. A state holiday in Kedah.', '吉打苏丹官方华诞，仅吉打放假。', 'Hari keputeraan rasmi Sultan Kedah. Cuti negeri Kedah.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-06-15', 2025, 'Birthday of the Sultan of Kedah', '吉打苏丹华诞', 'Hari Keputeraan Sultan Kedah', 'state', 'Kedah', 'Official birthday of the Sultan of Kedah. A state holiday in Kedah.', '吉打苏丹官方华诞，仅吉打放假。', 'Hari keputeraan rasmi Sultan Kedah. Cuti negeri Kedah.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-06-21', 2026, 'Birthday of the Sultan of Kedah', '吉打苏丹华诞', 'Hari Keputeraan Sultan Kedah', 'state', 'Kedah', 'Official birthday of the Sultan of Kedah. A state holiday in Kedah.', '吉打苏丹官方华诞，仅吉打放假。', 'Hari keputeraan rasmi Sultan Kedah. Cuti negeri Kedah.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-07-07', 2024, 'George Town World Heritage Day', '乔治市世界遗产日', 'Hari Ulang Tahun Perisytiharan Tapak Warisan Dunia', 'state', 'Pulau Pinang', 'Marks the UNESCO World Heritage listing of George Town. A state holiday in Pulau Pinang.', '纪念乔治市列入联合国教科文组织世界遗产，槟城州假期。', 'Ulang tahun George Town sebagai Tapak Warisan Dunia UNESCO. Cuti negeri Pulau Pinang.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-07-07', 2025, 'George Town World Heritage Day', '乔治市世界遗产日', 'Hari Ulang Tahun Perisytiharan Tapak Warisan Dunia', 'state', 'Pulau Pinang', 'Marks the UNESCO World Heritage listing of George Town. A state holiday in Pulau Pinang.', '纪念乔治市列入联合国教科文组织世界遗产，槟城州假期。', 'Ulang tahun George Town sebagai Tapak Warisan Dunia UNESCO. Cuti negeri Pulau Pinang.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-07-07', 2026, 'George Town World Heritage Day', '乔治市世界遗产日', 'Hari Ulang Tahun Perisytiharan Tapak Warisan Dunia', 'state', 'Pulau Pinang', 'Marks the UNESCO World Heritage listing of George Town. A state holiday in Pulau Pinang.', '纪念乔治市列入联合国教科文组织世界遗产，槟城州假期。', 'Ulang tahun George Town sebagai Tapak Warisan Dunia UNESCO. Cuti negeri Pulau Pinang.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-07-13', 2024, 'Birthday of the Yang di-Pertua Negeri of Pulau Pinang', '槟城州元首华诞', 'Hari Jadi Yang di-Pertua Negeri Pulau Pinang', 'state', 'Pulau Pinang', 'Birthday of the Yang di-Pertua Negeri of Pulau Pinang. A state holiday in Pulau Pinang.', '槟城州元首华诞，仅槟城放假。', 'Hari jadi Yang di-Pertua Negeri Pulau Pinang. Cuti negeri Pulau Pinang.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-07-12', 2025, 'Birthday of the Yang di-Pertua Negeri of Pulau Pinang', '槟城州元首华诞', 'Hari Jadi Yang di-Pertua Negeri Pulau Pinang', 'state', 'Pulau Pinang', 'Birthday of the Yang di-Pertua Negeri of Pulau Pinang. A state holiday in Pulau Pinang.', '槟城州元首华诞，仅槟城放假。', 'Hari jadi Yang di-Pertua Negeri Pulau Pinang. Cuti negeri Pulau Pinang.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-07-11', 2026, 'Birthday of the Yang di-Pertua Negeri of Pulau Pinang', '槟城州元首华诞', 'Hari Jadi Yang di-Pertua Negeri Pulau Pinang', 'state', 'Pulau Pinang', 'Birthday of the Yang di-Pertua Negeri of Pulau Pinang. A state holiday in Pulau Pinang.', '槟城州元首华诞，仅槟城放假。', 'Hari jadi Yang di-Pertua Negeri Pulau Pinang. Cuti negeri Pulau Pinang.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-08-11', 2024, 'Hari Hol Almarhum Sultan Iskandar', '苏丹依斯干达忌辰', 'Hari Hol Almarhum Sultan Iskandar', 'state', 'Johor', 'Hari Hol Almarhum Sultan Iskandar. A state holiday in Johor.', '苏丹依斯干达忌辰，仅柔佛放假。', 'Hari Hol Almarhum Sultan Iskandar. Cuti negeri Johor.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-08-12', 2025, 'Hari Hol Almarhum Sultan Iskandar', '苏丹依斯干达忌辰', 'Hari Hol Almarhum Sultan Iskandar', 'state', 'Johor', 'Hari Hol Almarhum Sultan Iskandar. A state holiday in Johor.', '苏丹依斯干达忌辰，仅柔佛放假。', 'Hari Hol Almarhum Sultan Iskandar. Cuti negeri Johor.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-07-21', 2026, 'Hari Hol Almarhum Sultan Iskandar', '苏丹依斯干达忌辰', 'Hari Hol Almarhum Sultan Iskandar', 'state', 'Johor', 'Hari Hol Almarhum Sultan Iskandar. A state holiday in Johor.', '苏丹依斯干达忌辰，仅柔佛放假。', 'Hari Hol Almarhum Sultan Iskandar. Cuti negeri Johor.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-07-22', 2024, 'Sarawak Day', '砂拉越日', 'Hari Sarawak', 'state', 'Sarawak', 'Sarawak Day on 22 July commemorates Sarawak self-government. A state holiday in Sarawak.', '砂拉越日（7月22日）纪念砂拉越自治，仅砂拉越放假。', 'Hari Sarawak pada 22 Julai, memperingati pemerintahan sendiri Sarawak. Cuti negeri Sarawak.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-07-22', 2025, 'Sarawak Day', '砂拉越日', 'Hari Sarawak', 'state', 'Sarawak', 'Sarawak Day on 22 July commemorates Sarawak self-government. A state holiday in Sarawak.', '砂拉越日（7月22日）纪念砂拉越自治，仅砂拉越放假。', 'Hari Sarawak pada 22 Julai, memperingati pemerintahan sendiri Sarawak. Cuti negeri Sarawak.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-07-22', 2026, 'Sarawak Day', '砂拉越日', 'Hari Sarawak', 'state', 'Sarawak', 'Sarawak Day on 22 July commemorates Sarawak self-government. A state holiday in Sarawak.', '砂拉越日（7月22日）纪念砂拉越自治，仅砂拉越放假。', 'Hari Sarawak pada 22 Julai, memperingati pemerintahan sendiri Sarawak. Cuti negeri Sarawak.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-07-30', 2024, 'Birthday of the Sultan of Pahang', '彭亨苏丹华诞', 'Hari Keputeraan Sultan Pahang', 'state', 'Pahang', 'Official birthday of the Sultan of Pahang. A state holiday in Pahang.', '彭亨苏丹官方华诞，仅彭亨放假。', 'Hari keputeraan rasmi Sultan Pahang. Cuti negeri Pahang.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-07-30', 2025, 'Birthday of the Sultan of Pahang', '彭亨苏丹华诞', 'Hari Keputeraan Sultan Pahang', 'state', 'Pahang', 'Official birthday of the Sultan of Pahang. A state holiday in Pahang.', '彭亨苏丹官方华诞，仅彭亨放假。', 'Hari keputeraan rasmi Sultan Pahang. Cuti negeri Pahang.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-07-31', 2026, 'Birthday of the Sultan of Pahang', '彭亨苏丹华诞', 'Hari Keputeraan Sultan Pahang', 'state', 'Pahang', 'Official birthday of the Sultan of Pahang. A state holiday in Pahang.', '彭亨苏丹官方华诞，仅彭亨放假。', 'Hari keputeraan rasmi Sultan Pahang. Cuti negeri Pahang.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-08-24', 2024, 'Birthday of the Yang di-Pertua Negeri of Melaka', '马六甲州元首华诞', 'Hari Jadi Yang di-Pertua Negeri Melaka', 'state', 'Melaka', 'Birthday of the Yang di-Pertua Negeri of Melaka on 24 August. A state holiday in Melaka.', '马六甲州元首华诞，每年8月24日。', 'Hari jadi Yang di-Pertua Negeri Melaka pada 24 Ogos. Cuti negeri Melaka.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-08-24', 2025, 'Birthday of the Yang di-Pertua Negeri of Melaka', '马六甲州元首华诞', 'Hari Jadi Yang di-Pertua Negeri Melaka', 'state', 'Melaka', 'Birthday of the Yang di-Pertua Negeri of Melaka on 24 August. A state holiday in Melaka.', '马六甲州元首华诞，每年8月24日。', 'Hari jadi Yang di-Pertua Negeri Melaka pada 24 Ogos. Cuti negeri Melaka.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-08-24', 2026, 'Birthday of the Yang di-Pertua Negeri of Melaka', '马六甲州元首华诞', 'Hari Jadi Yang di-Pertua Negeri Melaka', 'state', 'Melaka', 'Birthday of the Yang di-Pertua Negeri of Melaka on 24 August. A state holiday in Melaka.', '马六甲州元首华诞，每年8月24日。', 'Hari jadi Yang di-Pertua Negeri Melaka pada 24 Ogos. Cuti negeri Melaka.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-09-16', 2024, 'Prophet Muhammad''s Birthday (Maulidur Rasul)', '先知诞辰', 'Maulidur Rasul', 'federal', NULL, 'Maulidur Rasul commemorates the birthday of Prophet Muhammad. A federal public holiday.', '先知穆罕默德诞辰，全国联邦公共假期。', 'Maulidur Rasul, hari keputeraan Nabi Muhammad. Cuti umum persekutuan.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-09-05', 2025, 'Prophet Muhammad''s Birthday (Maulidur Rasul)', '先知诞辰', 'Maulidur Rasul', 'federal', NULL, 'Maulidur Rasul commemorates the birthday of Prophet Muhammad. A federal public holiday.', '先知穆罕默德诞辰，全国联邦公共假期。', 'Maulidur Rasul, hari keputeraan Nabi Muhammad. Cuti umum persekutuan.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-08-25', 2026, 'Prophet Muhammad''s Birthday (Maulidur Rasul)', '先知诞辰', 'Maulidur Rasul', 'federal', NULL, 'Maulidur Rasul commemorates the birthday of Prophet Muhammad. A federal public holiday.', '先知穆罕默德诞辰，全国联邦公共假期。', 'Maulidur Rasul, hari keputeraan Nabi Muhammad. Cuti umum persekutuan.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-08-31', 2024, 'National Day', '国庆日', 'Hari Kebangsaan', 'federal', NULL, 'National Day marks Malaya independence on 31 August 1957. A federal public holiday.', '国庆日纪念1957年8月31日马来亚独立，全国联邦公共假期。', 'Hari Kebangsaan / Hari Merdeka pada 31 Ogos 1957. Cuti umum persekutuan.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-08-31', 2025, 'National Day', '国庆日', 'Hari Kebangsaan', 'federal', NULL, 'National Day marks Malaya independence on 31 August 1957. A federal public holiday.', '国庆日纪念1957年8月31日马来亚独立，全国联邦公共假期。', 'Hari Kebangsaan / Hari Merdeka pada 31 Ogos 1957. Cuti umum persekutuan.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-08-31', 2026, 'National Day', '国庆日', 'Hari Kebangsaan', 'federal', NULL, 'National Day marks Malaya independence on 31 August 1957. A federal public holiday.', '国庆日纪念1957年8月31日马来亚独立，全国联邦公共假期。', 'Hari Kebangsaan / Hari Merdeka pada 31 Ogos 1957. Cuti umum persekutuan.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-09-01', 2025, 'National Day (Replacement)', '国庆日（补假）', 'Hari Kebangsaan (Cuti Ganti)', 'federal', NULL, 'Replacement holiday when National Day falls on a weekly rest day.', '国庆日适逢每周休息日时的补假。', 'Cuti ganti Hari Kebangsaan apabila 31 Ogos jatuh pada hari rehat mingguan.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-09-16', 2024, 'Malaysia Day', '马来西亚日', 'Hari Malaysia', 'federal', NULL, 'Malaysia Day on 16 September commemorates the formation of Malaysia in 1963.', '马来西亚日（9月16日）纪念1963年马来西亚成立。', 'Hari Malaysia pada 16 September, memperingati pembentukan Malaysia pada 1963.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-09-16', 2025, 'Malaysia Day', '马来西亚日', 'Hari Malaysia', 'federal', NULL, 'Malaysia Day on 16 September commemorates the formation of Malaysia in 1963.', '马来西亚日（9月16日）纪念1963年马来西亚成立。', 'Hari Malaysia pada 16 September, memperingati pembentukan Malaysia pada 1963.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-09-16', 2026, 'Malaysia Day', '马来西亚日', 'Hari Malaysia', 'federal', NULL, 'Malaysia Day on 16 September commemorates the formation of Malaysia in 1963.', '马来西亚日（9月16日）纪念1963年马来西亚成立。', 'Hari Malaysia pada 16 September, memperingati pembentukan Malaysia pada 1963.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-09-29', 2024, 'Birthday of the Sultan of Kelantan', '吉兰丹苏丹华诞', 'Hari Keputeraan Sultan Kelantan', 'state', 'Kelantan', 'First day of the Sultan of Kelantan official birthday. A state holiday in Kelantan.', '吉兰丹苏丹华诞第一天，仅吉兰丹放假。', 'Hari pertama keputeraan Sultan Kelantan. Cuti negeri Kelantan.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-09-29', 2025, 'Birthday of the Sultan of Kelantan', '吉兰丹苏丹华诞', 'Hari Keputeraan Sultan Kelantan', 'state', 'Kelantan', 'First day of the Sultan of Kelantan official birthday. A state holiday in Kelantan.', '吉兰丹苏丹华诞第一天，仅吉兰丹放假。', 'Hari pertama keputeraan Sultan Kelantan. Cuti negeri Kelantan.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-09-29', 2026, 'Birthday of the Sultan of Kelantan', '吉兰丹苏丹华诞', 'Hari Keputeraan Sultan Kelantan', 'state', 'Kelantan', 'First day of the Sultan of Kelantan official birthday. A state holiday in Kelantan.', '吉兰丹苏丹华诞第一天，仅吉兰丹放假。', 'Hari pertama keputeraan Sultan Kelantan. Cuti negeri Kelantan.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-09-30', 2024, 'Birthday of the Sultan of Kelantan (Second Day)', '吉兰丹苏丹华诞第二天', 'Hari Keputeraan Sultan Kelantan (Hari Kedua)', 'state', 'Kelantan', 'Second day of the Sultan of Kelantan official birthday. A state holiday in Kelantan.', '吉兰丹苏丹华诞第二天，仅吉兰丹放假。', 'Hari kedua keputeraan Sultan Kelantan. Cuti negeri Kelantan.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-09-30', 2025, 'Birthday of the Sultan of Kelantan (Second Day)', '吉兰丹苏丹华诞第二天', 'Hari Keputeraan Sultan Kelantan (Hari Kedua)', 'state', 'Kelantan', 'Second day of the Sultan of Kelantan official birthday. A state holiday in Kelantan.', '吉兰丹苏丹华诞第二天，仅吉兰丹放假。', 'Hari kedua keputeraan Sultan Kelantan. Cuti negeri Kelantan.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-09-30', 2026, 'Birthday of the Sultan of Kelantan (Second Day)', '吉兰丹苏丹华诞第二天', 'Hari Keputeraan Sultan Kelantan (Hari Kedua)', 'state', 'Kelantan', 'Second day of the Sultan of Kelantan official birthday. A state holiday in Kelantan.', '吉兰丹苏丹华诞第二天，仅吉兰丹放假。', 'Hari kedua keputeraan Sultan Kelantan. Cuti negeri Kelantan.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-10-05', 2024, 'Birthday of the Yang di-Pertua Negeri of Sabah', '沙巴州元首华诞', 'Hari Jadi Yang di-Pertua Negeri Sabah', 'state', 'Sabah', 'Birthday of the Yang di-Pertua Negeri of Sabah. A state holiday in Sabah.', '沙巴州元首华诞，仅沙巴放假。', 'Hari jadi Yang di-Pertua Negeri Sabah. Cuti negeri Sabah.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-10-04', 2025, 'Birthday of the Yang di-Pertua Negeri of Sabah', '沙巴州元首华诞', 'Hari Jadi Yang di-Pertua Negeri Sabah', 'state', 'Sabah', 'Birthday of the Yang di-Pertua Negeri of Sabah. A state holiday in Sabah.', '沙巴州元首华诞，仅沙巴放假。', 'Hari jadi Yang di-Pertua Negeri Sabah. Cuti negeri Sabah.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-03-30', 2026, 'Birthday of the Yang di-Pertua Negeri of Sabah', '沙巴州元首华诞', 'Hari Jadi Yang di-Pertua Negeri Sabah', 'state', 'Sabah', 'Birthday of the Yang di-Pertua Negeri of Sabah. A state holiday in Sabah.', '沙巴州元首华诞，仅沙巴放假。', 'Hari jadi Yang di-Pertua Negeri Sabah. Cuti negeri Sabah.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-10-12', 2024, 'Birthday of the Yang di-Pertua Negeri of Sarawak', '砂拉越州元首华诞', 'Hari Jadi Yang di-Pertua Negeri Sarawak', 'state', 'Sarawak', 'Birthday of the Yang di-Pertua Negeri of Sarawak. A state holiday in Sarawak.', '砂拉越州元首华诞，仅砂拉越放假。', 'Hari jadi Yang di-Pertua Negeri Sarawak. Cuti negeri Sarawak.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-10-11', 2025, 'Birthday of the Yang di-Pertua Negeri of Sarawak', '砂拉越州元首华诞', 'Hari Jadi Yang di-Pertua Negeri Sarawak', 'state', 'Sarawak', 'Birthday of the Yang di-Pertua Negeri of Sarawak. A state holiday in Sarawak.', '砂拉越州元首华诞，仅砂拉越放假。', 'Hari jadi Yang di-Pertua Negeri Sarawak. Cuti negeri Sarawak.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-10-10', 2026, 'Birthday of the Yang di-Pertua Negeri of Sarawak', '砂拉越州元首华诞', 'Hari Jadi Yang di-Pertua Negeri Sarawak', 'state', 'Sarawak', 'Birthday of the Yang di-Pertua Negeri of Sarawak. A state holiday in Sarawak.', '砂拉越州元首华诞，仅砂拉越放假。', 'Hari jadi Yang di-Pertua Negeri Sarawak. Cuti negeri Sarawak.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-10-31', 2024, 'Deepavali', '屠妖节', 'Deepavali', 'federal', 'Johor, Kedah, Kelantan, Melaka, Negeri Sembilan, Pahang, Pulau Pinang, Perak, Perlis, Sabah, Selangor, Terengganu, Kuala Lumpur, Labuan, Putrajaya', 'Deepavali, the Hindu festival of lights. A federal holiday except in Sarawak.', '印度教屠妖节（光明节）。联邦假期，砂拉越除外。', 'Deepavali, perayaan cahaya komuniti Hindu. Cuti umum kecuali Sarawak.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-10-20', 2025, 'Deepavali', '屠妖节', 'Deepavali', 'federal', 'Johor, Kedah, Kelantan, Melaka, Negeri Sembilan, Pahang, Pulau Pinang, Perak, Perlis, Sabah, Selangor, Terengganu, Kuala Lumpur, Labuan, Putrajaya', 'Deepavali, the Hindu festival of lights. A federal holiday except in Sarawak.', '印度教屠妖节（光明节）。联邦假期，砂拉越除外。', 'Deepavali, perayaan cahaya komuniti Hindu. Cuti umum kecuali Sarawak.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-11-08', 2026, 'Deepavali', '屠妖节', 'Deepavali', 'federal', 'Johor, Kedah, Kelantan, Melaka, Negeri Sembilan, Pahang, Pulau Pinang, Perak, Perlis, Sabah, Selangor, Terengganu, Kuala Lumpur, Labuan, Putrajaya', 'Deepavali, the Hindu festival of lights. A federal holiday except in Sarawak.', '印度教屠妖节（光明节）。联邦假期，砂拉越除外。', 'Deepavali, perayaan cahaya komuniti Hindu. Cuti umum kecuali Sarawak.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-11-09', 2026, 'Deepavali (Replacement)', '屠妖节（补假）', 'Deepavali (Cuti Ganti)', 'federal', 'Johor, Kedah, Kelantan, Melaka, Negeri Sembilan, Pahang, Pulau Pinang, Perak, Perlis, Sabah, Selangor, Terengganu, Kuala Lumpur, Labuan, Putrajaya', 'Replacement holiday when Deepavali falls on a weekend rest day.', '屠妖节适逢周末休息日时的补假。', 'Cuti ganti Deepavali apabila tarikh rasmi jatuh pada hujung minggu.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-11-01', 2024, 'Birthday of the Sultan of Perak', '霹雳苏丹华诞', 'Hari Keputeraan Sultan Perak', 'state', 'Perak', 'Official birthday of the Sultan of Perak. A state holiday in Perak.', '霹雳苏丹官方华诞，仅霹雳放假。', 'Hari keputeraan rasmi Sultan Perak. Cuti negeri Perak.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-11-07', 2025, 'Birthday of the Sultan of Perak', '霹雳苏丹华诞', 'Hari Keputeraan Sultan Perak', 'state', 'Perak', 'Official birthday of the Sultan of Perak. A state holiday in Perak.', '霹雳苏丹官方华诞，仅霹雳放假。', 'Hari keputeraan rasmi Sultan Perak. Cuti negeri Perak.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-11-06', 2026, 'Birthday of the Sultan of Perak', '霹雳苏丹华诞', 'Hari Keputeraan Sultan Perak', 'state', 'Perak', 'Official birthday of the Sultan of Perak. A state holiday in Perak.', '霹雳苏丹官方华诞，仅霹雳放假。', 'Hari keputeraan rasmi Sultan Perak. Cuti negeri Perak.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-12-11', 2024, 'Birthday of the Sultan of Selangor', '雪兰莪苏丹华诞', 'Hari Keputeraan Sultan Selangor', 'state', 'Selangor', 'Official birthday of the Sultan of Selangor on 11 December. A state holiday in Selangor.', '雪兰莪苏丹官方华诞，每年12月11日。', 'Hari keputeraan rasmi Sultan Selangor pada 11 Disember. Cuti negeri Selangor.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-12-11', 2025, 'Birthday of the Sultan of Selangor', '雪兰莪苏丹华诞', 'Hari Keputeraan Sultan Selangor', 'state', 'Selangor', 'Official birthday of the Sultan of Selangor on 11 December. A state holiday in Selangor.', '雪兰莪苏丹官方华诞，每年12月11日。', 'Hari keputeraan rasmi Sultan Selangor pada 11 Disember. Cuti negeri Selangor.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-12-11', 2026, 'Birthday of the Sultan of Selangor', '雪兰莪苏丹华诞', 'Hari Keputeraan Sultan Selangor', 'state', 'Selangor', 'Official birthday of the Sultan of Selangor on 11 December. A state holiday in Selangor.', '雪兰莪苏丹官方华诞，每年12月11日。', 'Hari keputeraan rasmi Sultan Selangor pada 11 Disember. Cuti negeri Selangor.', 1);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-12-24', 2024, 'Christmas Eve', '圣诞夜', 'Christmas Eve', 'state', 'Sabah', 'Christmas Eve is a state public holiday in Sabah.', '圣诞夜为沙巴州公共假期。', 'Malam Krismas. Cuti negeri di Sabah.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-12-24', 2025, 'Christmas Eve', '圣诞夜', 'Christmas Eve', 'state', 'Sabah', 'Christmas Eve is a state public holiday in Sabah.', '圣诞夜为沙巴州公共假期。', 'Malam Krismas. Cuti negeri di Sabah.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-12-24', 2026, 'Christmas Eve', '圣诞夜', 'Christmas Eve', 'state', 'Sabah', 'Christmas Eve is a state public holiday in Sabah.', '圣诞夜为沙巴州公共假期。', 'Malam Krismas. Cuti negeri di Sabah.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-12-25', 2024, 'Christmas Day', '圣诞节', 'Hari Krismas', 'federal', NULL, 'Christmas Day on 25 December is a federal public holiday throughout Malaysia.', '圣诞节（12月25日）为全国联邦公共假期。', 'Hari Krismas pada 25 Disember. Cuti umum persekutuan di seluruh Malaysia.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-12-25', 2025, 'Christmas Day', '圣诞节', 'Hari Krismas', 'federal', NULL, 'Christmas Day on 25 December is a federal public holiday throughout Malaysia.', '圣诞节（12月25日）为全国联邦公共假期。', 'Hari Krismas pada 25 Disember. Cuti umum persekutuan di seluruh Malaysia.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-12-25', 2026, 'Christmas Day', '圣诞节', 'Hari Krismas', 'federal', NULL, 'Christmas Day on 25 December is a federal public holiday throughout Malaysia.', '圣诞节（12月25日）为全国联邦公共假期。', 'Hari Krismas pada 25 Disember. Cuti umum persekutuan di seluruh Malaysia.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-02-14', 2024, 'Valentine''s Day', '情人节', 'Hari Valentine', 'observance', NULL, 'Valentine''s Day is an international observance for love and friendship. Not a public holiday.', '情人节为国际观察日，不是马来西亚公共假期。', 'Hari Valentine, hari pemerhatian antarabangsa untuk kasih sayang. Bukan cuti umum.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-02-14', 2025, 'Valentine''s Day', '情人节', 'Hari Valentine', 'observance', NULL, 'Valentine''s Day is an international observance for love and friendship. Not a public holiday.', '情人节为国际观察日，不是马来西亚公共假期。', 'Hari Valentine, hari pemerhatian antarabangsa untuk kasih sayang. Bukan cuti umum.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-02-14', 2026, 'Valentine''s Day', '情人节', 'Hari Valentine', 'observance', NULL, 'Valentine''s Day is an international observance for love and friendship. Not a public holiday.', '情人节为国际观察日，不是马来西亚公共假期。', 'Hari Valentine, hari pemerhatian antarabangsa untuk kasih sayang. Bukan cuti umum.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-02-24', 2024, 'Chap Goh Mei', '元宵节', 'Chap Goh Mei', 'observance', NULL, 'Chap Goh Mei is the 15th day of Chinese New Year. A cultural observance, not a public holiday.', '农历正月十五元宵节，属文化观察日，不是公共假期。', 'Chap Goh Mei, hari ke-15 Tahun Baharu Cina. Pemerhatian budaya, bukan cuti umum.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-02-12', 2025, 'Chap Goh Mei', '元宵节', 'Chap Goh Mei', 'observance', NULL, 'Chap Goh Mei is the 15th day of Chinese New Year. A cultural observance, not a public holiday.', '农历正月十五元宵节，属文化观察日，不是公共假期。', 'Chap Goh Mei, hari ke-15 Tahun Baharu Cina. Pemerhatian budaya, bukan cuti umum.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-03-03', 2026, 'Chap Goh Mei', '元宵节', 'Chap Goh Mei', 'observance', NULL, 'Chap Goh Mei is the 15th day of Chinese New Year. A cultural observance, not a public holiday.', '农历正月十五元宵节，属文化观察日，不是公共假期。', 'Chap Goh Mei, hari ke-15 Tahun Baharu Cina. Pemerhatian budaya, bukan cuti umum.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-03-08', 2024, 'International Women''s Day', '国际妇女节', 'Hari Wanita Antarabangsa', 'observance', NULL, 'International Women''s Day on 8 March. An observance, not a Malaysian public holiday.', '3月8日国际妇女节，属观察日，不是公共假期。', 'Hari Wanita Antarabangsa pada 8 Mac. Pemerhatian, bukan cuti umum.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-03-08', 2025, 'International Women''s Day', '国际妇女节', 'Hari Wanita Antarabangsa', 'observance', NULL, 'International Women''s Day on 8 March. An observance, not a Malaysian public holiday.', '3月8日国际妇女节，属观察日，不是公共假期。', 'Hari Wanita Antarabangsa pada 8 Mac. Pemerhatian, bukan cuti umum.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-03-08', 2026, 'International Women''s Day', '国际妇女节', 'Hari Wanita Antarabangsa', 'observance', NULL, 'International Women''s Day on 8 March. An observance, not a Malaysian public holiday.', '3月8日国际妇女节，属观察日，不是公共假期。', 'Hari Wanita Antarabangsa pada 8 Mac. Pemerhatian, bukan cuti umum.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-04-04', 2024, 'Qing Ming Festival', '清明节', 'Festival Qing Ming', 'observance', NULL, 'Qing Ming is a Chinese ancestral remembrance day. A cultural observance.', '清明节为华人祭祖日，属文化观察日。', 'Festival Qing Ming, hari menghormati nenek moyang. Pemerhatian budaya Cina.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-04-04', 2025, 'Qing Ming Festival', '清明节', 'Festival Qing Ming', 'observance', NULL, 'Qing Ming is a Chinese ancestral remembrance day. A cultural observance.', '清明节为华人祭祖日，属文化观察日。', 'Festival Qing Ming, hari menghormati nenek moyang. Pemerhatian budaya Cina.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-04-05', 2026, 'Qing Ming Festival', '清明节', 'Festival Qing Ming', 'observance', NULL, 'Qing Ming is a Chinese ancestral remembrance day. A cultural observance.', '清明节为华人祭祖日，属文化观察日。', 'Festival Qing Ming, hari menghormati nenek moyang. Pemerhatian budaya Cina.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-05-12', 2024, 'Mother''s Day', '母亲节', 'Hari Ibu', 'observance', NULL, 'Mother''s Day is observed on the second Sunday of May. Not a public holiday.', '母亲节为五月第二个星期日，不是公共假期。', 'Hari Ibu, Ahad kedua bulan Mei. Pemerhatian, bukan cuti umum.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-05-11', 2025, 'Mother''s Day', '母亲节', 'Hari Ibu', 'observance', NULL, 'Mother''s Day is observed on the second Sunday of May. Not a public holiday.', '母亲节为五月第二个星期日，不是公共假期。', 'Hari Ibu, Ahad kedua bulan Mei. Pemerhatian, bukan cuti umum.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-05-10', 2026, 'Mother''s Day', '母亲节', 'Hari Ibu', 'observance', NULL, 'Mother''s Day is observed on the second Sunday of May. Not a public holiday.', '母亲节为五月第二个星期日，不是公共假期。', 'Hari Ibu, Ahad kedua bulan Mei. Pemerhatian, bukan cuti umum.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-05-16', 2024, 'Teachers'' Day', '教师节', 'Hari Guru', 'observance', NULL, 'Malaysia Teachers'' Day is observed on 16 May. An education observance, not a public holiday.', '马来西亚教师节为5月16日，属教育观察日，不是公共假期。', 'Hari Guru Malaysia pada 16 Mei. Pemerhatian pendidikan, bukan cuti umum.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-05-16', 2025, 'Teachers'' Day', '教师节', 'Hari Guru', 'observance', NULL, 'Malaysia Teachers'' Day is observed on 16 May. An education observance, not a public holiday.', '马来西亚教师节为5月16日，属教育观察日，不是公共假期。', 'Hari Guru Malaysia pada 16 Mei. Pemerhatian pendidikan, bukan cuti umum.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-05-16', 2026, 'Teachers'' Day', '教师节', 'Hari Guru', 'observance', NULL, 'Malaysia Teachers'' Day is observed on 16 May. An education observance, not a public holiday.', '马来西亚教师节为5月16日，属教育观察日，不是公共假期。', 'Hari Guru Malaysia pada 16 Mei. Pemerhatian pendidikan, bukan cuti umum.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-06-16', 2024, 'Father''s Day', '父亲节', 'Hari Bapa', 'observance', NULL, 'Father''s Day is observed on the third Sunday of June. Not a public holiday.', '父亲节为六月第三个星期日，不是公共假期。', 'Hari Bapa, Ahad ketiga bulan Jun. Pemerhatian, bukan cuti umum.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-06-15', 2025, 'Father''s Day', '父亲节', 'Hari Bapa', 'observance', NULL, 'Father''s Day is observed on the third Sunday of June. Not a public holiday.', '父亲节为六月第三个星期日，不是公共假期。', 'Hari Bapa, Ahad ketiga bulan Jun. Pemerhatian, bukan cuti umum.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-06-21', 2026, 'Father''s Day', '父亲节', 'Hari Bapa', 'observance', NULL, 'Father''s Day is observed on the third Sunday of June. Not a public holiday.', '父亲节为六月第三个星期日，不是公共假期。', 'Hari Bapa, Ahad ketiga bulan Jun. Pemerhatian, bukan cuti umum.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-06-10', 2024, 'Dragon Boat Festival', '端午节', 'Festival Perahu Naga', 'observance', NULL, 'Dragon Boat Festival (Duanwu) is a Chinese cultural observance.', '端午节为华人文化观察日。', 'Festival Perahu Naga (Duanwu). Pemerhatian budaya Cina.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-05-31', 2025, 'Dragon Boat Festival', '端午节', 'Festival Perahu Naga', 'observance', NULL, 'Dragon Boat Festival (Duanwu) is a Chinese cultural observance.', '端午节为华人文化观察日。', 'Festival Perahu Naga (Duanwu). Pemerhatian budaya Cina.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-06-19', 2026, 'Dragon Boat Festival', '端午节', 'Festival Perahu Naga', 'observance', NULL, 'Dragon Boat Festival (Duanwu) is a Chinese cultural observance.', '端午节为华人文化观察日。', 'Festival Perahu Naga (Duanwu). Pemerhatian budaya Cina.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-08-18', 2024, 'Hungry Ghost Festival', '中元节', 'Festival Hungry Ghost', 'observance', NULL, 'Hungry Ghost Festival / Zhongyuan is a Chinese cultural observance.', '中元节为华人文化观察日。', 'Festival Hungry Ghost / Zhongyuan. Pemerhatian budaya Cina.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-09-06', 2025, 'Hungry Ghost Festival', '中元节', 'Festival Hungry Ghost', 'observance', NULL, 'Hungry Ghost Festival / Zhongyuan is a Chinese cultural observance.', '中元节为华人文化观察日。', 'Festival Hungry Ghost / Zhongyuan. Pemerhatian budaya Cina.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-08-27', 2026, 'Hungry Ghost Festival', '中元节', 'Festival Hungry Ghost', 'observance', NULL, 'Hungry Ghost Festival / Zhongyuan is a Chinese cultural observance.', '中元节为华人文化观察日。', 'Festival Hungry Ghost / Zhongyuan. Pemerhatian budaya Cina.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-09-17', 2024, 'Mid-Autumn Festival', '中秋节', 'Festival Pertengahan Musim Luruh', 'observance', NULL, 'Mid-Autumn Festival is a Chinese cultural observance celebrated with mooncakes.', '中秋节为华人文化观察日，传统上会吃月饼。', 'Festival Pertengahan Musim Luruh. Pemerhatian budaya Cina dengan kuih bulan.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-10-06', 2025, 'Mid-Autumn Festival', '中秋节', 'Festival Pertengahan Musim Luruh', 'observance', NULL, 'Mid-Autumn Festival is a Chinese cultural observance celebrated with mooncakes.', '中秋节为华人文化观察日，传统上会吃月饼。', 'Festival Pertengahan Musim Luruh. Pemerhatian budaya Cina dengan kuih bulan.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-09-25', 2026, 'Mid-Autumn Festival', '中秋节', 'Festival Pertengahan Musim Luruh', 'observance', NULL, 'Mid-Autumn Festival is a Chinese cultural observance celebrated with mooncakes.', '中秋节为华人文化观察日，传统上会吃月饼。', 'Festival Pertengahan Musim Luruh. Pemerhatian budaya Cina dengan kuih bulan.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-10-31', 2024, 'Halloween', '万圣节前夜', 'Halloween', 'observance', NULL, 'Halloween on 31 October is a popular observance, not a Malaysian public holiday.', '10月31日万圣节前夜属流行观察日，不是马来西亚公共假期。', 'Halloween pada 31 Oktober. Pemerhatian popular, bukan cuti umum Malaysia.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-10-31', 2025, 'Halloween', '万圣节前夜', 'Halloween', 'observance', NULL, 'Halloween on 31 October is a popular observance, not a Malaysian public holiday.', '10月31日万圣节前夜属流行观察日，不是马来西亚公共假期。', 'Halloween pada 31 Oktober. Pemerhatian popular, bukan cuti umum Malaysia.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-10-31', 2026, 'Halloween', '万圣节前夜', 'Halloween', 'observance', NULL, 'Halloween on 31 October is a popular observance, not a Malaysian public holiday.', '10月31日万圣节前夜属流行观察日，不是马来西亚公共假期。', 'Halloween pada 31 Oktober. Pemerhatian popular, bukan cuti umum Malaysia.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2024-12-31', 2024, 'New Year''s Eve', '除夕', 'Malam Tahun Baharu', 'observance', NULL, 'New Year''s Eve on 31 December is widely celebrated but is not a public holiday.', '12月31日除夕常有庆祝活动，但不是公共假期。', 'Malam Tahun Baharu pada 31 Disember. Pemerhatian, bukan cuti umum.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2025-12-31', 2025, 'New Year''s Eve', '除夕', 'Malam Tahun Baharu', 'observance', NULL, 'New Year''s Eve on 31 December is widely celebrated but is not a public holiday.', '12月31日除夕常有庆祝活动，但不是公共假期。', 'Malam Tahun Baharu pada 31 Disember. Pemerhatian, bukan cuti umum.', 0);
INSERT INTO holidays (holiday_date, year, name_en, name_zh, name_ms, type, states, description_en, description_zh, description_ms, is_birthday) VALUES ('2026-12-31', 2026, 'New Year''s Eve', '除夕', 'Malam Tahun Baharu', 'observance', NULL, 'New Year''s Eve on 31 December is widely celebrated but is not a public holiday.', '12月31日除夕常有庆祝活动，但不是公共假期。', 'Malam Tahun Baharu pada 31 Disember. Pemerhatian, bukan cuti umum.', 0);

SET FOREIGN_KEY_CHECKS = 1;
-- Total rows: 189
